# Generated by Django 4.2.5 on 2023-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=20)),
                ('receipe_description', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
